config/routes.rb
Rails.application.routes.draw do
  resources :breastfeedings
  resources :babies
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'breastfeedings#index'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/baby.rb
class Baby < ApplicationRecord
  has_many :breastfeedings, dependent: :destroy

  enum gener: [:hombre, :mujer]

  def to_s
    name
  end

  def total_taked
    breastfeedings.pluck(:volume).reduce(&:+)
  end

  def total_q
    breastfeedings.count
  end

  def daily_quantity
    breastfeedings.where(created_at: Time.zone.now.beginning_of_day..Time.zone.now.end_of_day).count#[Date.today.beginning_of_day,Date.today.end_of_day]).count
  end

  def last_breast
    breastfeedings.last&.created_at&.to_date
  end

  def daily_volumne
    breastfeedings.where(created_at: Time.zone.now.beginning_of_day..Time.zone.now.end_of_day).pluck(:volume).reduce(&:+)
  end

  def daily_minutes
    breastfeedings.where(created_at: Time.zone.now.beginning_of_day..Time.zone.now.end_of_day).pluck(:minutes).reduce(&:+)
  end
end

app/models/breastfeeding.rb
class Breastfeeding < ApplicationRecord
  belongs_to :baby
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/babies_controller.rb
class BabiesController < ApplicationController
  before_action :set_baby, only: [:show, :edit, :update, :destroy]

  # GET /babies
  # GET /babies.json
  def index
    @babies = Baby.all
  end

  # GET /babies/1
  # GET /babies/1.json
  def show
  end

  # GET /babies/new
  def new
    @baby = Baby.new
  end

  # GET /babies/1/edit
  def edit
  end

  # POST /babies
  # POST /babies.json
  def create
    @baby = Baby.new(baby_params)

    respond_to do |format|
      if @baby.save
        format.html { redirect_to @baby, notice: 'Baby was successfully created.' }
        format.json { render :show, status: :created, location: @baby }
      else
        format.html { render :new }
        format.json { render json: @baby.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /babies/1
  # PATCH/PUT /babies/1.json
  def update
    respond_to do |format|
      if @baby.update(baby_params)
        format.html { redirect_to @baby, notice: 'Baby was successfully updated.' }
        format.json { render :show, status: :ok, location: @baby }
      else
        format.html { render :edit }
        format.json { render json: @baby.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /babies/1
  # DELETE /babies/1.json
  def destroy
    @baby.destroy
    respond_to do |format|
      format.html { redirect_to babies_url, notice: 'Baby was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_baby
      @baby = Baby.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def baby_params
      params.require(:baby).permit(:name, :gener)
    end
end

app/controllers/breastfeedings_controller.rb
class BreastfeedingsController < ApplicationController
  before_action :set_breastfeeding, only: [:show, :edit, :update, :destroy]

  # GET /breastfeedings
  # GET /breastfeedings.json
  def index
    @breastfeedings = Breastfeeding.all
  end

  # GET /breastfeedings/1
  # GET /breastfeedings/1.json
  def show
    
  end

  # GET /breastfeedings/new
  def new
    @breastfeeding = Breastfeeding.new
    @babies = Baby.all
  end

  # GET /breastfeedings/1/edit
  def edit
    @baby = Baby.all
  
  end

  # POST /breastfeedings
  # POST /breastfeedings.json
  def create
    @breastfeeding = Breastfeeding.new(breastfeeding_params)

    respond_to do |format|
      if @breastfeeding.save
        format.html { redirect_to @breastfeeding, notice: 'Breastfeeding was successfully created.' }
        format.json { render :show, status: :created, location: @breastfeeding }
      else
        format.html { render :new }
        format.json { render json: @breastfeeding.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /breastfeedings/1
  # PATCH/PUT /breastfeedings/1.json
  def update
    respond_to do |format|
      if @breastfeeding.update(breastfeeding_params)
        format.html { redirect_to @breastfeeding, notice: 'Breastfeeding was successfully updated.' }
        format.json { render :show, status: :ok, location: @breastfeeding }
      else
        format.html { render :edit }
        format.json { render json: @breastfeeding.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /breastfeedings/1
  # DELETE /breastfeedings/1.json
  def destroy
    @breastfeeding.destroy
    respond_to do |format|
      format.html { redirect_to breastfeedings_url, notice: 'Breastfeeding was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_breastfeeding
      @breastfeeding = Breastfeeding.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def breastfeeding_params
      params.require(:breastfeeding).permit(:volume, :minutes, :baby_id )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/babies_helper.rb
module BabiesHelper
end

app/helpers/breastfeedings_helper.rb
module BreastfeedingsHelper
end

app/views/babies/_form.html.erb
<div class="row">
  <div class="col-md offset-md-1">
    <%= form_with(model: baby, local: true) do |form| %>
      <% if baby.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(baby.errors.count, "error") %> prohibited this baby from being saved:</h2>
          <ul>
            <% baby.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class="field">
        <%= form.label :name, "Nombre" %>
        <%= form.text_field :name %>
      </div>
      <div class="field">
        <%= form.label :gener, "Genero" %>
        <%= form.select :gener, Baby.geners.keys %>
      </div>
      <div class="actions">
        <%= form.submit "Guardar"%>
      </div>
    <% end %>
  </div>
</div>

app/views/babies/edit.html.erb
<div class="row">
  <div class="col-md offset-md-1">
    <h1>Editando Bebé</h1>
    <%= render 'form', baby: @baby %>
    <%= link_to 'Mostrar', @baby %> |
    <%= link_to 'Volver', babies_path %>
  </div>
</div>

app/views/babies/index.html.erb
<div class="row-4">
  <div class="col-md offset-md-12">
   <div class="jumbotron">
    <p id="notice"><%= notice %></p>
    <h1>Bebés</h1>
    <table class="table">
      <thead>
        <tr>
          <th>Nombre</th>
          <th>Género</th>
          <th>Total Tomado</th>
          <th>Total Volumen</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
        <% @babies.each do |baby| %>
          <tr>
            <td><%= baby.name %></td>
            <td><%= baby.gener %></td> 
            <td><%= baby.total_q %></td>
            <td><%= baby.total_taked %></td>
            <td><%= link_to 'Show', baby %></td>
            <td><%= link_to 'Edit', edit_baby_path(baby) %></td>
            <td><%= link_to 'Destroy', baby, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <br>
    <%= link_to 'Nuevo Bebé', new_baby_path, class:"btn btn-success" %>
    <%= link_to 'Lactancias', root_path, class:"btn btn-warning" %>
     </div>
  </div>
</div>

app/views/babies/new.html.erb
<div class="row">
  <div class="col-md offset-md-1">
    <h1>Nuevo Bebé</h1>
    <%= render 'form', baby: @baby %>
    <%= link_to 'Volver', babies_path %>
  </div>
</div>

app/views/babies/show.html.erb
<div class="row">
  <div class="col-md offset-md-1">
    <p id="notice"><%= notice %></p>
    <h1><%= @baby.name %></h1>
    <p>
      <strong>Gener:</strong>
      <%= @baby.gener %>
    </p>
    <p>
      <strong>Cantidad Diaria:</strong>
      <%= @baby.daily_quantity %>
    </p>
    <p>
      <strong>Ultima Tomada  :</strong>
      <%= @baby.last_breast %>
    </p>
    <p>
      <strong>Volumen Diario:</strong>
      <%= @baby.daily_volumne %>
    </p>
    <p>
      <strong>Minutos diarios:</strong>
      <%= @baby.daily_minutes %>
    </p>

    <%= link_to 'Edit', edit_baby_path(@baby) %> |
    <%= link_to 'Back', babies_path %>
  </div>
</div>

app/views/breastfeedings/_form.html.erb
<div class="row">
  <div class="col-md offset-md-1">
    <%= form_with(model: breastfeeding, local: true) do |form| %>
      <% if breastfeeding.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(breastfeeding.errors.count, "error") %> prohibited this breastfeeding from being saved:</h2>

          <ul>
            <% breastfeeding.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class="field">
        <%= form.label :volume, "Volumen" %>
        <%= form.number_field :volume %>
      </div>
      <div class="field">
        <%= form.label :minutes , "Minutos"%>
        <%= form.number_field :minutes %>
      </div>
       <div class="field">
        <%= form.label :baby_id %>
        <!--<%= form.number_field :baby_id %>-->
        <%=  form.collection_select :baby_id, Baby.all, :id,  :name %>
      </div>
      <div class="actions ">
        <%= form.submit "Guardar" %>
      </div>
    <% end %>
  </div>
</div>

app/views/breastfeedings/edit.html.erb
<div class="row">
  <div class="col-md offset-md-1">
    <h1>Editando </h1>
    <%= render 'form', breastfeeding: @breastfeeding %>
    <%= link_to 'Mostrar', @breastfeeding %> 
    <%= link_to 'Volver', breastfeedings_path %>
  </div>
</div>

app/views/breastfeedings/index.html.erb
<div class="row">

  <div class="col-md offset-md-1">

    <p id="notice"><%= notice %></p>

    <h1>Lactancia</h1>

    <table class="table">
      <thead class="text-center">
        <tr>
          <th>Volumen</th>
          <th>Minutos</th>
          <th>Bebé</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody class="text-center" >
        <% @breastfeedings.each do |breastfeeding| %>
          <tr >
            <td ><%= breastfeeding.volume %></td>
            <td><%= breastfeeding.minutes %></td>
            <td><%= breastfeeding.baby %></td> 
            <td><%= link_to 'Mostrar', breastfeeding %></td>
            <td><%= link_to 'Editar', edit_breastfeeding_path(breastfeeding) %></td>
            <td><%= link_to 'Destruir', breastfeeding, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <br>
    <%= link_to 'Nueva Lactancia', new_breastfeeding_path , class:"btn btn-success" %>
    <%= link_to 'Administrar Bebés', babies_path , class:"btn btn-primary"%>
  </div>
</div>

app/views/breastfeedings/new.html.erb
<div class="row">
  <div class="col-md offset-md-1">
    <h1>Nueva Lactancia</h1>
      <%= render 'form', breastfeeding: @breastfeeding %>
      <%= link_to 'Volver', breastfeedings_path %>
  </div>
</div>

app/views/breastfeedings/show.html.erb
<div class="row">
    <div class="col-md offset-md-1">
    <p id="notice"><%= notice %></p>
    <p>
      <strong>Volume:</strong>
      <%= @breastfeeding.volume %>
    </p>
    <p>
      <strong>Minutes:</strong>
      <%= @breastfeeding.minutes %>
    </p>
    <p>
      <strong>Baby:</strong>
      <%= @breastfeeding.baby_id %>
    </p>
    <%= link_to 'Edit', edit_breastfeeding_path(@breastfeeding) %> |
    <%= link_to 'Back', breastfeedings_path %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Babies</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css " integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>

  <body id="babies">
    <%= yield %>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  </body>
</html>